#cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-1-Aguascalientes.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-2-BajaCalifornia.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-3-BajaCaliforniaSur.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-4-Campeche.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-5-CoahuiladeZaragoza.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-6-Colima.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-7-Chiapas.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-8-Chihuahua.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-9-CiudadMX.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-10-Durango.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-11-Guanajuato.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-12-Guerrero.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-13-Hidalgo.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-14-Jalisco.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-15-Mx.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-16-Michoacan.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-17-Morelos.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-18-Nayarit.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-19-NuevoLeon.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-20-Oaxaca.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-21-Puebla.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-22-Queretaro.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-23-QuintanaRoo.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-24-SLP­.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-25-Sinaloa.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-26-Sonora.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-27-Tabasco.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-28-Tamaulipas.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-29-Tlaxcala.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-30-Veracruz.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-31-Yucatan.sh
cat SCRIPTS/Descarga-1-Aguascalientes.sh > SCRIPTS/Descarga-32-Zacatecas.sh